[build]
  base = "apps/web-dashboard"
  command = "pnpm install --frozen-lockfile && pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  PNPM_VERSION = "9"
  TURBO_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "pnpm -w --filter @apatte/web-dashboard dev"
  targetPort = 3000
